rental_management/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rentals/', include('rentals.urls', namespace='rentals')),
]

rentals/urls.py
from django.urls import path

from rentals import views

app_name = 'rentals'

urlpatterns = [
    path('list/', views.ReservationListView.as_view(), name='reservation_list'),
    path('create-rental/', views.RentalCreateView.as_view(), name='rental_create'),
    path('create-reservation/', views.ReservationCreateView.as_view(), name='reservation_create'),
]

rentals/models.py
from django.db import models
from django.utils import timezone


class Rental(models.Model):
    name = models.CharField(max_length=128)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self) -> str:
        return f'{self.name}'


class Reservation(models.Model):
    rental = models.ForeignKey(Rental, on_delete=models.PROTECT)
    checkin = models.DateField()
    checkout = models.DateField()
    created_at = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['rental', 'checkin']

rentals/views.py
from typing import Any, Dict

from django.db import models
from django.db.models import OuterRef, QuerySet, Subquery
from django.urls import reverse
from django.views.generic import CreateView, ListView

from rentals.models import Rental, Reservation


class ReservationListView(ListView):
    model = Reservation
    paginate_by = 50
    context_object_name = 'reservations'

    def get_queryset(self) -> 'QuerySet[Reservation]':
        previous_reservations = Reservation.objects.filter(
            rental_id=OuterRef('rental_id'),
            checkin__lt=OuterRef('checkin'),
        ).order_by('-checkin')
        return Reservation.objects.all().annotate(
            previous_reservation_id=Subquery(previous_reservations.values('id')[:1], output_field=models.CharField())
        ).select_related('rental')


class RentalCreateView(CreateView):
    model = Rental
    fields = ['name']

    def get_success_url(self) -> str:
        return reverse('rentals:rental_create')

    def get_context_data(self, **kwargs) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['rentals'] = Rental.objects.all()
        return context


class ReservationCreateView(CreateView):
    model = Reservation
    fields = ['rental', 'checkin', 'checkout']

    def get_context_data(self, **kwargs) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['rentals_count'] = Rental.objects.count()
        return context

    def get_success_url(self) -> str:
        return reverse('rentals:reservation_create')

rentals/templates/rentals/base.html
<!DOCTYPE html>
<html>
<head>
  <title>Rentals</title>
  <style>
    ul {
      margin: 5mm;
      padding: 0;
    }
    ul li {
      display: inline;
      margin: 5mm;
    }
  </style>
</head>
<body>

<ul>
  <li><a href="{% url 'rentals:reservation_list' %}">Reservation list</a></li>
  <li><a href="{% url 'rentals:reservation_create' %}">Add reservation</a></li>
  <li><a href="{% url 'rentals:rental_create' %}">Add rental</a></li>
</ul>

{% block content %}{% endblock %}

</body>
</html>

rentals/templates/rentals/rental_form.html
{% extends 'rentals/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

    <h1>Add a rental</h1>

    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit">
    </form>

    <h1>Your rentals</h1>

    {% if rentals %}
        <table>
            <thead>
                <tr>
                    <td>ID</td>
                    <td>Name</td>
                    <td>Created at</td>
                </tr>
            </thead>
            <tbody>
                {% for rental in rentals %}
                    <tr>
                        <td>{{ rental.id }}</td>
                        <td>{{ rental.name }}</td>
                        <td>{{ rental.created_at }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>You do not currently have any rentals.</p>
    {% endif %}

{% endblock %}

rentals/templates/rentals/reservation_form.html
{% extends 'rentals/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

    {% if rentals_count %}

        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit">
        </form>

    {% else %}

        <p>
            On this page you will be able to add reservations to your rentals. You currently have 0 rentals.
            <a href="{% url 'rentals:rental_create' %}">Add</a> one now.
        </p>

    {% endif %}

{% endblock %}

rentals/templates/rentals/reservation_list.html
{% extends 'rentals/base.html' %}

{% block content %}

  {% if reservations %}
    <table>
      <thead>
        <tr>
          <td>Rental_name</td>
          <td>ID</td>
          <td>Checkin</td>
          <td>Checkout</td>
          <td>Previous reservation, ID</td>
        </tr>
      </thead>
      <tbody>
        {% for reservation in reservations %}
          <tr>
            <td>{{ reservation.rental.name }}</td>
            <td>Res-{{ reservation.id }}</td>
            <td>{{ reservation.checkin }}</td>
            <td>{{ reservation.checkout }}</td>
            <td>{% if reservation.previous_reservation_id %}Res-{{ reservation.previous_reservation_id }}{% else %}-{% endif %}</td>
          </tr>
        {% endfor %}
      </tbody>

    </table>
  {% else %}
    <p>There are no reservations. <a href="{% url 'rentals:reservation_create' %}">Add</a> one now.</p>
  {% endif %}

{% endblock %}